# Generated by Django 5.2.8 on 2025-11-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafeguardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_serial', models.CharField(default='844585', max_length=20)),
                ('report_datetime', models.DateTimeField(auto_now_add=True)),
                ('engine_off_timestamp', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distance_to_road_m', models.FloatField()),
                ('is_safe', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'safeguard_reports',
                'ordering': ['-engine_off_timestamp'],
            },
        ),
    ]
